//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chillde.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chillde.Services.Resources.CategoryLanguage", typeof(CategoryLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anklets.
        /// </summary>
        public static string Anklets {
            get {
                return ResourceManager.GetString("Anklets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm Bands.
        /// </summary>
        public static string Arm_Bands {
            get {
                return ResourceManager.GetString("Arm Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm Warmers.
        /// </summary>
        public static string Arm_Warmers {
            get {
                return ResourceManager.GetString("Arm Warmers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art &amp; Collectibles.
        /// </summary>
        public static string Art___Collectibles {
            get {
                return ResourceManager.GetString("Art & Collectibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Trading Cards.
        /// </summary>
        public static string Artist_Trading_Cards {
            get {
                return ResourceManager.GetString("Artist Trading Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Accessories.
        /// </summary>
        public static string Baby_Accessories {
            get {
                return ResourceManager.GetString("Baby Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bags &amp; Purses.
        /// </summary>
        public static string Bags___Purses {
            get {
                return ResourceManager.GetString("Bags & Purses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangles.
        /// </summary>
        public static string Bangles {
            get {
                return ResourceManager.GetString("Bangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbells.
        /// </summary>
        public static string Barbells {
            get {
                return ResourceManager.GetString("Barbells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beaded Necklaces.
        /// </summary>
        public static string Beaded_Necklaces {
            get {
                return ResourceManager.GetString("Beaded Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belly Chains.
        /// </summary>
        public static string Belly_Chains {
            get {
                return ResourceManager.GetString("Belly Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belly Rings.
        /// </summary>
        public static string Belly_Rings {
            get {
                return ResourceManager.GetString("Belly Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt Buckles.
        /// </summary>
        public static string Belt_Buckles {
            get {
                return ResourceManager.GetString("Belt Buckles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belts.
        /// </summary>
        public static string Belts {
            get {
                return ResourceManager.GetString("Belts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belts &amp; Suspenders.
        /// </summary>
        public static string Belts___Suspenders {
            get {
                return ResourceManager.GetString("Belts & Suspenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bib Necklaces.
        /// </summary>
        public static string Bib_Necklaces {
            get {
                return ResourceManager.GetString("Bib Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Blank_Books {
            get {
                return ResourceManager.GetString("Blank Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Jewelry.
        /// </summary>
        public static string Body_Jewelry {
            get {
                return ResourceManager.GetString("Body Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Book_Accessories {
            get {
                return ResourceManager.GetString("Book Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Book_Sets___Collections {
            get {
                return ResourceManager.GetString("Book Sets & Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Books__Movies___Music {
            get {
                return ResourceManager.GetString("Books, Movies & Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouquets.
        /// </summary>
        public static string Bouquets {
            get {
                return ResourceManager.GetString("Bouquets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouquets &amp; Corsages.
        /// </summary>
        public static string Bouquets___Corsages {
            get {
                return ResourceManager.GetString("Bouquets & Corsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutonnières.
        /// </summary>
        public static string Boutonnières {
            get {
                return ResourceManager.GetString("Boutonnières", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boys&apos; Clothing.
        /// </summary>
        public static string Boys__Clothing {
            get {
                return ResourceManager.GetString("Boys\' Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracelets.
        /// </summary>
        public static string Bracelets {
            get {
                return ResourceManager.GetString("Bracelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridal Churas.
        /// </summary>
        public static string Bridal_Churas {
            get {
                return ResourceManager.GetString("Bridal Churas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooches.
        /// </summary>
        public static string Brooches {
            get {
                return ResourceManager.GetString("Brooches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brooches, Pins &amp; Clips.
        /// </summary>
        public static string Brooches__Pins___Clips {
            get {
                return ResourceManager.GetString("Brooches, Pins & Clips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameo Necklaces.
        /// </summary>
        public static string Cameo_Necklaces {
            get {
                return ResourceManager.GetString("Cameo Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Wallets.
        /// </summary>
        public static string Chain_Wallets {
            get {
                return ResourceManager.GetString("Chain Wallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chandelier Earrings.
        /// </summary>
        public static string Chandelier_Earrings {
            get {
                return ResourceManager.GetString("Chandelier Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm Bracelets.
        /// </summary>
        public static string Charm_Bracelets {
            get {
                return ResourceManager.GetString("Charm Bracelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm Necklaces.
        /// </summary>
        public static string Charm_Necklaces {
            get {
                return ResourceManager.GetString("Charm Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbook Covers.
        /// </summary>
        public static string Checkbook_Covers {
            get {
                return ResourceManager.GetString("Checkbook Covers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Children_s_Books {
            get {
                return ResourceManager.GetString("Children\'s Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Photo Props.
        /// </summary>
        public static string Children_s_Photo_Props {
            get {
                return ResourceManager.GetString("Children\'s Photo Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip-On Earrings.
        /// </summary>
        public static string Clip_On_Earrings {
            get {
                return ResourceManager.GetString("Clip-On Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing &amp; Shoe Clips.
        /// </summary>
        public static string Clothing___Shoe_Clips {
            get {
                return ResourceManager.GetString("Clothing & Shoe Clips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Earrings.
        /// </summary>
        public static string Cluster_Earrings {
            get {
                return ResourceManager.GetString("Cluster Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectibles.
        /// </summary>
        public static string Collectibles {
            get {
                return ResourceManager.GetString("Collectibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Coloring_Books {
            get {
                return ResourceManager.GetString("Coloring Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Comics___Graphic_Novels {
            get {
                return ResourceManager.GetString("Comics & Graphic Novels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsages.
        /// </summary>
        public static string Corsages {
            get {
                return ResourceManager.GetString("Corsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume Accessories.
        /// </summary>
        public static string Costume_Accessories {
            get {
                return ResourceManager.GetString("Costume Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume Goggles.
        /// </summary>
        public static string Costume_Goggles {
            get {
                return ResourceManager.GetString("Costume Goggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume Weapons.
        /// </summary>
        public static string Costume_Weapons {
            get {
                return ResourceManager.GetString("Costume Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cremation &amp; Memorial Jewelry.
        /// </summary>
        public static string Cremation___Memorial_Jewelry {
            get {
                return ResourceManager.GetString("Cremation & Memorial Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuff Bracelets.
        /// </summary>
        public static string Cuff_Bracelets {
            get {
                return ResourceManager.GetString("Cuff Bracelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolls &amp; Miniatures.
        /// </summary>
        public static string Dolls___Miniatures {
            get {
                return ResourceManager.GetString("Dolls & Miniatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing &amp; Illustration.
        /// </summary>
        public static string Drawing___Illustration {
            get {
                return ResourceManager.GetString("Drawing & Illustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dress Clips.
        /// </summary>
        public static string Dress_Clips {
            get {
                return ResourceManager.GetString("Dress Clips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Gloves.
        /// </summary>
        public static string Driving_Gloves {
            get {
                return ResourceManager.GetString("Driving Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earrings.
        /// </summary>
        public static string Earrings {
            get {
                return ResourceManager.GetString("Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Hair.
        /// </summary>
        public static string Facial_Hair {
            get {
                return ResourceManager.GetString("Facial Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Arts.
        /// </summary>
        public static string Fiber_Arts {
            get {
                return ResourceManager.GetString("Fiber Arts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Art Ceramics.
        /// </summary>
        public static string Fine_Art_Ceramics {
            get {
                return ResourceManager.GetString("Fine Art Ceramics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraternal &amp; Class Rings.
        /// </summary>
        public static string Fraternal___Class_Rings {
            get {
                return ResourceManager.GetString("Fraternal & Class Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardening &amp; Work Gloves.
        /// </summary>
        public static string Gardening___Work_Gloves {
            get {
                return ResourceManager.GetString("Gardening & Work Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender-Neutral Adult Clothing.
        /// </summary>
        public static string Gender_Neutral_Adult_Clothing {
            get {
                return ResourceManager.GetString("Gender-Neutral Adult Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghép Hình.
        /// </summary>
        public static string Ghép_Hình {
            get {
                return ResourceManager.GetString("Ghép Hình", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Gig_Bags___Instrument_Cases {
            get {
                return ResourceManager.GetString("Gig Bags & Instrument Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Art.
        /// </summary>
        public static string Glass_Art {
            get {
                return ResourceManager.GetString("Glass Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves &amp; Mittens.
        /// </summary>
        public static string Gloves___Mittens {
            get {
                return ResourceManager.GetString("Gloves & Mittens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halloween Candy Bags.
        /// </summary>
        public static string Halloween_Candy_Bags {
            get {
                return ResourceManager.GetString("Halloween Candy Bags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Chain.
        /// </summary>
        public static string Hand_Chain {
            get {
                return ResourceManager.GetString("Hand Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Instrument_Straps {
            get {
                return ResourceManager.GetString("Instrument Straps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry.
        /// </summary>
        public static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry Sets.
        /// </summary>
        public static string Jewelry_Sets {
            get {
                return ResourceManager.GetString("Jewelry Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry Storage.
        /// </summary>
        public static string Jewelry_Storage {
            get {
                return ResourceManager.GetString("Jewelry Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadas.
        /// </summary>
        public static string Kadas {
            get {
                return ResourceManager.GetString("Kadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lariat &amp; Y Necklaces.
        /// </summary>
        public static string Lariat___Y_Necklaces {
            get {
                return ResourceManager.GetString("Lariat & Y Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lip Rings.
        /// </summary>
        public static string Lip_Rings {
            get {
                return ResourceManager.GetString("Lip Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockets.
        /// </summary>
        public static string Lockets {
            get {
                return ResourceManager.GetString("Lockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masks &amp; Prosthetics.
        /// </summary>
        public static string Masks___Prosthetics {
            get {
                return ResourceManager.GetString("Masks & Prosthetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi Rings.
        /// </summary>
        public static string Midi_Rings {
            get {
                return ResourceManager.GetString("Midi Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mittens &amp; Muffs.
        /// </summary>
        public static string Mittens___Muffs {
            get {
                return ResourceManager.GetString("Mittens & Muffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosaics.
        /// </summary>
        public static string Mosaics {
            get {
                return ResourceManager.GetString("Mosaics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Stone Rings.
        /// </summary>
        public static string Multi_Stone_Rings {
            get {
                return ResourceManager.GetString("Multi-Stone Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Musical_Instruments {
            get {
                return ResourceManager.GetString("Musical Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necklaces.
        /// </summary>
        public static string Necklaces {
            get {
                return ResourceManager.GetString("Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nipple Jewelr.
        /// </summary>
        public static string Nipple_Jewelr {
            get {
                return ResourceManager.GetString("Nipple Jewelr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose Rings &amp; Studs.
        /// </summary>
        public static string Nose_Rings___Studs {
            get {
                return ResourceManager.GetString("Nose Rings & Studs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting.
        /// </summary>
        public static string Painting {
            get {
                return ResourceManager.GetString("Painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography.
        /// </summary>
        public static string Photography {
            get {
                return ResourceManager.GetString("Photography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Picks___Slides {
            get {
                return ResourceManager.GetString("Picks & Slides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins &amp; Badges.
        /// </summary>
        public static string Pins___Badges {
            get {
                return ResourceManager.GetString("Pins & Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Watches.
        /// </summary>
        public static string Pocket_Watches {
            get {
                return ResourceManager.GetString("Pocket Watches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints.
        /// </summary>
        public static string Prints {
            get {
                return ResourceManager.GetString("Prints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Recorded_Audio {
            get {
                return ResourceManager.GetString("Recorded Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Dishes.
        /// </summary>
        public static string Ring_Dishes {
            get {
                return ResourceManager.GetString("Ring Dishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Guards &amp; Spacers.
        /// </summary>
        public static string Ring_Guards___Spacers {
            get {
                return ResourceManager.GetString("Ring Guards & Spacers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Trees.
        /// </summary>
        public static string Ring_Trees {
            get {
                return ResourceManager.GetString("Ring Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings.
        /// </summary>
        public static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shawl Pins.
        /// </summary>
        public static string Shawl_Pins {
            get {
                return ResourceManager.GetString("Shawl Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoe Clips.
        /// </summary>
        public static string Shoe_Clips {
            get {
                return ResourceManager.GetString("Shoe Clips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solitaire Rings.
        /// </summary>
        public static string Solitaire_Rings {
            get {
                return ResourceManager.GetString("Solitaire Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stackable Rings.
        /// </summary>
        public static string Stackable_Rings {
            get {
                return ResourceManager.GetString("Stackable Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunglasses &amp; Eyewear.
        /// </summary>
        public static string Sunglasses___Eyewear {
            get {
                return ResourceManager.GetString("Sunglasses & Eyewear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweater Clips.
        /// </summary>
        public static string Sweater_Clips {
            get {
                return ResourceManager.GetString("Sweater Clips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Cases &amp; Tins.
        /// </summary>
        public static string Video_Cases___Tins {
            get {
                return ResourceManager.GetString("Video Cases & Tins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallets &amp; Money Clips.
        /// </summary>
        public static string Wallets___Money_Clips {
            get {
                return ResourceManager.GetString("Wallets & Money Clips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wands.
        /// </summary>
        public static string Wands {
            get {
                return ResourceManager.GetString("Wands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Bands &amp; Straps.
        /// </summary>
        public static string Watch_Bands___Straps {
            get {
                return ResourceManager.GetString("Watch Bands & Straps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Necklaces.
        /// </summary>
        public static string Watch_Necklaces {
            get {
                return ResourceManager.GetString("Watch Necklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Rings.
        /// </summary>
        public static string Watch_Rings {
            get {
                return ResourceManager.GetString("Watch Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watches.
        /// </summary>
        public static string Watches {
            get {
                return ResourceManager.GetString("Watches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings.
        /// </summary>
        public static string Wings {
            get {
                return ResourceManager.GetString("Wings", resourceCulture);
            }
        }
    }
}
